# Generated by Django 4.1.7 on 2023-03-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookieApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('expire_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('username', models.TextField()),
                ('isLogged', models.BooleanField(default=False)),
                ('cookie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenity.cookieapp')),
                ('current_channel_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='jenity.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenity.channel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenity.userapp')),
            ],
        ),
    ]
